<?php
namespace Jvital\Idml\SerializationClass\Idml\Enums;

class PageTransitionTypeOptions
{
    const BLINDS_TRANSITION = "BLINDS_TRANSITION";
    const BOX_TRANSITION = "BOX_TRANSITION";
    const COMB_TRANSITION = "COMB_TRANSITION";
    const COVER_TRANSITION = "COVER_TRANSITION";
    const DISSOLVE_TRANSITION = "DISSOLVE_TRANSITION";
    const FADE_TRANSITION = "FADE_TRANSITION";
    const NONE = "NONE";
    const PUSH_TRANSITION = "PUSH_TRANSITION";
    const SPLIT_TRANSITION = "SPLIT_TRANSITION";
    const UNCOVER_TRANSITION = "UNCOVER_TRANSITION";
    const WIPE_TRANSITION = "WIPE_TRANSITION";
    const ZOOM_IN_TRANSITION = "ZOOM_IN_TRANSITION";
    const ZOOM_OUT_TRANSITION = "ZOOM_OUT_TRANSITION";

}