<?php
namespace Jvital\Idml\SerializationClass\Idml\Ressources\Styles;
use JMS\Serializer\Annotation\XmlRoot;
use Jvital\Idml\SerializationClass\Idml\Trait\AutoLeadingAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\BaselineShiftAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\CapitalizationAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\FillColorAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\FirstLineIndentAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\FontStyleAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\HorizontalScaleAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\HyphenationAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\ImportedAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\JustificationAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\LastLineIndentAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\LeftIndentAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\LigaturesAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\NameAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\NextStyleAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\ParagraphBorderBottomLineWeightAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\ParagraphBorderLeftLineWeightAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\ParagraphBorderOnAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\ParagraphBorderRightLineWeightAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\ParagraphBorderTopLineWeightAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\PointSizeAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\Properties;
use Jvital\Idml\SerializationClass\Idml\Trait\RightIndentAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\SelfAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\SkewAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\SpaceAfterAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\SpaceBeforeAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\SplitDocumentAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\StrikeThroughOffsetAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\StrikeThroughWeightAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\StrikeThruAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\StrokeColorAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\StrokeWeightAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\TrackingAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\UnderlineAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\UnderlineOffsetAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\UnderlineWeightAttribute;
use Jvital\Idml\SerializationClass\Idml\Trait\VerticalScaleAttribute;

/** 
 * @XmlRoot("ParagraphStyle") 
 */
class ParagraphStyle
{

    use SelfAttribute;
    use NameAttribute;
    use ImportedAttribute;
    use SplitDocumentAttribute;
    use FillColorAttribute;
    use FontStyleAttribute;
    use NextStyleAttribute;
    use PointSizeAttribute;
    use LigaturesAttribute;
    use StrokeWeightAttribute;
    use TrackingAttribute;
    use CapitalizationAttribute;
    use StrokeColorAttribute;
    use LeftIndentAttribute;
    use RightIndentAttribute;
    use FirstLineIndentAttribute;
    use AutoLeadingAttribute;
    use HyphenationAttribute;
    use UnderlineAttribute;
    use SkewAttribute;
    use LastLineIndentAttribute;
    use JustificationAttribute;
    use UnderlineOffsetAttribute;
    use UnderlineWeightAttribute;
    use StrikeThroughOffsetAttribute;
    use StrikeThroughWeightAttribute;
    use StrikeThruAttribute;
    use HorizontalScaleAttribute;
    use BaselineShiftAttribute;
    use VerticalScaleAttribute;
    use SpaceBeforeAttribute; 
    use SpaceAfterAttribute; 
    use ParagraphBorderOnAttribute;
    use ParagraphBorderTopLineWeightAttribute;
    use ParagraphBorderBottomLineWeightAttribute;
    use ParagraphBorderLeftLineWeightAttribute;
    use ParagraphBorderRightLineWeightAttribute;
    use Properties;
}